name: CI-Docker

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker-Compose
      run:  docker-compose up -d
    - name: PS
      run:  docker-compose ps
    - name: Web Test via CURL
      run: cd simple_node_app && npm run test:docker
    - name: Webhook
      uses: joelwmale/webhook-action@master
      env:
        WEBHOOK_URL: 'http://localhost:18080'